version: '3.6'

services:
  app:
    image: wordpress@sha256:808d11c13cd0dec746a737e5f717a6b43f470ef197452657df1e71a163e6979e
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ahduser
      WORDPRESS_DB_PASSWORD: ahdpass
      WORDPRESS_DB_NAME: ahdpressdev
    volumes:
      - ../..:/workspaces:cached

  db:
    image: mariadb@sha256:4a1de8fa2a929944373d7421105500ff6f889ce90dcb883fbb2fdb070e4d427e
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: ahdcreativedev
      MYSQL_PASSWORD: ahdcreativepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql


volumes:
  db:
