version: '3.6'

services:
  app:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ahduser
      WORDPRESS_DB_PASSWORD: ahdpass
      WORDPRESS_DB_NAME: ahdpressdev
    volumes:
      - ../..:/workspaces:cached

  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: ahdcreativedev
      MYSQL_PASSWORD: ahdcreativepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql


volumes:
  db:
