version: '3.6'

services:
  app:
    image: wordpress@sha256:b2d7e3153c8a96f90305a3102fb6439335237fb1a9655b617d15c5168ce2f7a3
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ahduser
      WORDPRESS_DB_PASSWORD: ahdpass
      WORDPRESS_DB_NAME: ahdpressdev
    volumes:
      - ../..:/workspaces:cached

  db:
    image: mariadb@sha256:759869cb6f003234a95c6384cdee245b4bce7de26913fe607a8110362c0c007d
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: ahdcreativedev
      MYSQL_PASSWORD: ahdcreativepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql


volumes:
  db:
